version: 2

jobs: 
  website:
    docker:
      - image: cimg/python:3.9.7-node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - add_ssh_keys:
          fingerprints:
            - "34:c0:a9:93:bc:32:73:4c:8f:4a:c3:d1:f9:d0:9e:8a"
      - run:
          name: Set Git identity
          command: |
            git config --global user.email "robot@circleci.com"
            git config --global user.name "CircleCI"
      - restore_cache:
          keys:
          - v3-site-{{ checksum "site/package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            cd site
            npm install
      - save_cache:
          paths:
            - site/node_modules
          key: v3-site-{{ checksum "site/package-lock.json" }}
      - run:
          name: Building Site
          command: |
            cd site
            npm run build
      - run:
          name: Push to GitHub
          command: |
            cd dist
            cp ../site/_redirects .
            cp ../site/_headers .
            cp ../site/robots.txt .
            echo "schema.data.gouv.fr" > CNAME
            cd ../site
            npm run deploy
workflows:
  version: 2
  commit:
    jobs:
      - website:
          filters:
            branches:
              only:
                - master
  cron_fetch:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - website
