title: schema.data.gouv.fr
description: >
    schema.data.gouv.fr est l'initiative de la mission Etalab de référencement des schémas de données publiques pour la France.

twitter_username: etalab
github_username:  etalab
github_repository: etalab/schema.data.gouv.fr
url: https://schema.data.gouv.fr
lang: fr
permalink: pretty

i18n:
  en:
    edit: Edit this page
  fr:
    edit: Éditer cette page

sass:
    style: compressed

exclude:
  - README.md
  - build.sh
  - .circleci/circle.yml
  - Gemfile
  - Gemfile.lock
  - vendor

# Collection configuration
# Specify a directory to store all our collections in the same place
collections_dir: collections

# Metadata for our collections
collections:
  schemas:
    title: Schémas
    output: true
  documentation:
    title: Documentation
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: "schemas"
    values:
      layout: schema

theme: jekyll-theme-gouvfr

plugins:
  - jekyll-redirect-from
